"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Operador = void 0;
var Operador;
(function (Operador) {
    Operador["SUMA"] = "+";
    Operador["RESTA"] = "-";
    Operador["MULTIPLICACION"] = "*";
    Operador["DIVISION"] = "/";
    Operador["MODULO"] = "%";
    Operador["MENOS_UNARIO"] = "UMENOS";
    Operador["MAYOR_QUE"] = ">";
    Operador["MENOR_QUE"] = "<";
    Operador["IGUAL_IGUAL"] = "==";
    Operador["DIFERENTE_QUE"] = "!=";
    Operador["INCREMENTO"] = "INCREMENTO";
    Operador["DECREMENTO"] = "DECREMENTO";
    Operador["AND"] = "&&";
    Operador["OR"] = "||";
    Operador["NOT"] = "!";
    Operador["MAYOR_IGUAL_QUE"] = ">=";
    Operador["MENOR_IGUAL_QUE"] = "<=";
    Operador["POW"] = "POW";
    Operador["SQRT"] = "SQRT";
    Operador["LOG"] = "LOG";
    Operador["SENO"] = "SENO";
    Operador["COSENO"] = "COSENO";
    Operador["TAN"] = "TAN";
    Operador["CONCAT"] = "CONCAT";
    Operador["REPEAT"] = "REPEAT";
})(Operador = exports.Operador || (exports.Operador = {}));
