export enum Operador {
    SUMA = "+",
    RESTA = "-",
    MULTIPLICACION = "*",
    DIVISION = "/",
    MODULO = "%",
    MENOS_UNARIO = "UMENOS",
    MAYOR_QUE = ">",
    MENOR_QUE = "<",
    IGUAL_IGUAL = "==",
    DIFERENTE_QUE = "!=",
    INCREMENTO = "INCREMENTO",
    DECREMENTO = "DECREMENTO",
    AND = "&&",
    OR = "||",
    NOT = "!",
    MAYOR_IGUAL_QUE = ">=",
    MENOR_IGUAL_QUE = "<=",
    POW = "POW",
    SQRT = "SQRT",
    LOG = "LOG",
    SENO = "SENO",
    COSENO = "COSENO",
    TAN = "TAN",
    CONCAT = "CONCAT",
    REPEAT = "REPEAT",
}
